name: get-stock-history-schedule

on:
  schedule:
    - cron: "20 4 * * 1-5" # runs at 4:00 GMT everyday

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      - name: install python packages
        with:
          python-version: ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        env:
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: python script_get_stock_history.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
